// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byimzdghhvskzrulfxkh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5aW16ZGdoaHZza3pydWxmeGtoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM2MDI5OTQsImV4cCI6MjA0OTE3ODk5NH0.KWdvbWonl6vJRp-mBRzverRUNIYoVa1KW-t7KpIYqOU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);